# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_api_development

test:
  <<: *default
  database: hello_rails_api_test

production:
  <<: *default
  database: hello_rails_api_production
  username: <%= ENV["HELLO_RAILS_API_DATABASE_USERNAME"] %>
  password: <%= ENV["HELLO_RAILS_API_DATABASE_PASSWORD"] %>
